version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: valgood-watchtower_server_1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    port: 8080:8181  
    environment:
      - TZ=$TZ
      - WATCHTOWER_CLEANUP=true                                        
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=36000                  
      #- WATCHTOWER_SCHEDULE=0 0 9 * * *
      #- WATCHTOWER_DEBUG=true   
  app_proxy:
    environment:
      APP_HOST: valgood-watchtower_server_1
      APP_PORT: 8181
      PROXY_AUTH_ADD: 'false'      